### PR TITLE
Add pip_freeze.yml

### PR DESCRIPTION
**Pull request by jladdjr**
Used by https://github.com/ansible/tower-qa/pull/1996/files to confirm that a JT sourced the correct custom virtualenv

### CODE REVIEW

**Comment by simfarm** [comment]
Pip isn't installed natively on a lot of the linux machines that we use for testing. I haven't taken a look at these tests so I'm not sure if this is needed.

**Comment by jlaska** [comment]
A few comments ... this playbook is very tightly coupled with a tower-qa use case that isn't very obvious in this repo stand-alone.  In other words, it's not obvious how this playbook adds value stand-alone.  

Unless expressly needed, you might consider capturing the fact `{{ ansible_distribution_version }}` instead of dropping into the shell.  You could also collect facts, and inspect the facts from tower-qa instead of the additional task.

If you need to inspect the contents of pip freeze, might it be worth capturing the output programmatically as a fact, so it could be inspected using pytest-ansible? 

Just thinking of ways to reduce any potential string manipulations.

**Comment by jladdjr** [comment]
@unlikelyzero - The playbook is meant to be run against localhost in which case it will use the version of pip in the current Tower venv (whether it's the default venv, or a custom one made by the user). I don't see this playbook necessarily getting used outside of the venv test suite. When used in the tests, pip will always be present in the Tower venv in which case I don't think we really need a sanity check on pip.

**Comment by jladdjr** [comment]
> A few comments ... this playbook is very tightly coupled with a tower-qa use case that isn't very obvious in this repo stand-alone

Makes sense. Sent out an e-mail to the test team floating the idea of creating a separate repo for test playbooks.

**Comment by jlaska** [comment]
Another thought, just use `run_command.yml`?

**Pull request closed without merging**
